"""
fetch_fonts.py
--------------
Self-host the web fonts so NO request ever goes to Google (privacy: a reader's IP never
reaches Google; supply-chain: no CDN font dependency). Fetches the exact woff2 files Google
Fonts would serve, keeps only the subsets Paksh needs (latin, latin-ext, devanagari - we are
English + Hindi), and writes a local static/fonts.css with the src rewritten to /static/fonts/.

Run once (and again only if the font list in static/index.html changes):
    py fetch_fonts.py

Then static/fonts/*.woff2 + static/fonts.css are committed and served same-origin. index.html
links /static/fonts.css instead of fonts.googleapis.com; the CSP drops the google font hosts.
"""

import re
import urllib.request
from pathlib import Path

# The EXACT families/axes the site uses (mirror of the <link> that was in static/index.html).
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400"
           "&family=Tiro+Devanagari+Hindi:ital@0;1"
           "&family=IBM+Plex+Sans:wght@400;500;600;700"
           "&family=IBM+Plex+Mono:wght@400;500;600"
           "&family=IBM+Plex+Sans+Devanagari:wght@400;500;600;700"
           "&display=swap")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/124.0 Safari/537.36")   # a modern UA makes Google serve woff2
KEEP_SUBSETS = {"latin", "latin-ext", "devanagari"}

ROOT = Path(__file__).resolve().parent
FONT_DIR = ROOT / "static" / "fonts"


def _get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    css = _get(CSS_URL)
    # Each face is:  /* subset */\n@font-face { ... src: url(...woff2) ...; }
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
    kept, dropped, downloaded = [], 0, {}
    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            dropped += 1
            continue
        m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block)
        if not m:
            continue
        url = m.group(1)
        fname = url.rsplit("/", 1)[-1]                      # unique content-hashed name
        if fname not in downloaded:
            (FONT_DIR / fname).write_bytes(_get(url, binary=True))
            downloaded[fname] = True
        # comment the subset for readability, rewrite src to the local path
        local = block.replace(url, "/static/fonts/%s" % fname)
        kept.append("/* %s */\n%s" % (subset, local))

    out = ("/* Self-hosted fonts (generated by fetch_fonts.py) - no request goes to Google.\n"
           "   Re-run fetch_fonts.py if the family list changes. */\n\n" + "\n\n".join(kept) + "\n")
    (ROOT / "static" / "fonts.css").write_text(out, encoding="utf-8")

    print(f"Kept {len(kept)} @font-face (subsets {sorted(KEEP_SUBSETS)}); dropped {dropped} other-subset faces.")
    print(f"Downloaded {len(downloaded)} woff2 -> static/fonts/  ({sum(f.stat().st_size for f in FONT_DIR.glob('*.woff2'))//1024} KB)")
    print("Wrote static/fonts.css")


if __name__ == "__main__":
    main()
