INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-8751', 'Russia intensifies attacks on Ukraine''s capital and infrastructure', 'रूस ने यूक्रेन की राजधानी और बुनियादी ढांचे पर हमले तेज किए', 'Crime & Law', 'World', 18, '2026-07-23T11:19:41.244364'::timestamptz, '2026-08-29T00:37:18.096903'::timestamptz, '2026-08-29T00:37:18.096903'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11978', 'Maharashtra Auto Drivers Get One-Year Marathi Learning Extension', 'महाराष्ट्र ऑटो चालकों को मराठी सीखने के लिए एक साल का विस्तार मिला', 'Society', 'India', 3, '2026-08-07T05:40:02.116566'::timestamptz, '2026-08-29T00:37:11.350467'::timestamptz, '2026-08-29T00:37:11.350467'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14274', 'Sailor on USS Abraham Lincoln Faces Charges After Suicide Attempt', 'यूएसएस अब्राहम लिंकन पर एक नाविक ने आत्महत्या के प्रयास के बाद आरोपों का सामना किया', 'Crime & Law', 'World', 5, '2026-08-14T00:27:13.639856'::timestamptz, '2026-08-28T14:49:10'::timestamptz, '2026-08-28T14:49:10'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14581', 'Asian Markets Rise Following Nvidia-Driven Wall Street Gains', 'Nvidia के नेतृत्व वाली वॉल स्ट्रीट की बढ़त के बाद एशियाई बाजारों में तेजी', 'Economy', 'World', 2, '2026-08-16T00:35:22.722047'::timestamptz, '2026-08-28T13:38:15.590296'::timestamptz, '2026-08-28T13:38:15.590296'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14362', 'Multiple Fatal Collisions Involving Public Transit Buses Reported', 'सार्वजनिक परिवहन बसों से जुड़ी कई घातक टक्करों की रिपोर्ट', 'Crime & Law', 'World', 2, '2026-08-16T00:35:21.237017'::timestamptz, '2026-08-28T00:44:32.169038'::timestamptz, '2026-08-28T00:44:32.169038'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15967', 'US Imposes Tariffs on Canadian Goods; Canada Vows Retaliation', 'अमेरिका ने कनाडाई सामानों पर लगाए टैरिफ; कनाडा ने जवाबी कार्रवाई की कसम खाई', 'Economy', 'World', 2, '2026-08-22T05:36:10.207329'::timestamptz, '2026-08-28T00:44:30.218759'::timestamptz, '2026-08-28T00:44:30.218759'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12133', 'NFL Teams Conduct Training Camp Practices', 'एनएफएल टीमों ने प्रशिक्षण शिविर का अभ्यास किया', 'Sports', 'World', 5, '2026-08-10T00:32:31.577518'::timestamptz, '2026-08-28T00:44:30.044768'::timestamptz, '2026-08-28T00:44:30.044768'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15680', 'Trump Unveils White House Helipad and Ballroom Construction', 'ट्रम्प ने व्हाइट हाउस हेलीपैड और बैलरूम निर्माण का अनावरण किया', 'Politics', 'World', 2, '2026-08-22T05:25:04.593056'::timestamptz, '2026-08-28T00:44:25.654715'::timestamptz, '2026-08-28T00:44:25.654715'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14854', 'Legal groups challenge Ontario''s cash bail system in court', 'कानूनी समूहों ने अदालत में ओंटारियो की नकद जमानत प्रणाली को चुनौती दी', 'Crime & Law', 'World', 2, '2026-08-16T23:57:09.465998'::timestamptz, '2026-08-27T19:43:57'::timestamptz, '2026-08-27T19:43:57'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-8962', 'India vs Sri Lanka Test Match Heads Towards Draw', 'भारत बनाम श्रीलंका टेस्ट मैच ड्रॉ की ओर बढ़ा', 'Sports', 'India', 18, '2026-07-26T09:06:00.606591'::timestamptz, '2026-08-27T13:17:53'::timestamptz, '2026-08-27T13:17:53'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15021', 'Five Teenagers Die in Wrong-Way M9 Motorway Collision', 'M9 मोटरवे पर गलत दिशा से आई गाड़ी की टक्कर में पांच किशोरों की मौत', 'Crime & Law', 'World', 2, '2026-08-18T05:22:28.644200'::timestamptz, '2026-08-27T00:54:12.184006'::timestamptz, '2026-08-27T00:54:12.184006'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14571', 'Lucknow students protest teacher shortage and poor amenities', 'लखनऊ में शिक्षकों की कमी और सुविधाओं के अभाव के खिलाफ छात्रों का विरोध प्रदर्शन', 'Society', 'India', 2, '2026-08-14T16:11:45.733715'::timestamptz, '2026-08-27T00:54:10.808094'::timestamptz, '2026-08-27T00:54:10.808094'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11841', 'Iran, Oman Discuss Joint Shipping Route in Strait of Hormuz', 'ईरान और ओमान ने होर्मुज जलडमरूमध्य में संयुक्त शिपिंग मार्ग पर चर्चा की', 'International', 'World', 10, '2026-08-07T06:43:26.745910'::timestamptz, '2026-08-27T00:54:05.725446'::timestamptz, '2026-08-27T00:54:05.725446'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13202', 'OpenAI Data Center Head Departs Amid Executive Exits', 'ओपनएआई के डेटा सेंटर प्रमुख ने कार्यकारी निकास के बीच छोड़ा पद', 'Politics', 'World', 4, '2026-08-11T21:02:55.164293'::timestamptz, '2026-08-25T21:30:00'::timestamptz, '2026-08-25T21:30:00'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15374', 'FIFA beaver statues auction raises over $170,000 in Toronto', 'टोरंटो में फीफा बीवर मूर्तियों की नीलामी से $170,000 से अधिक जुटाए गए', 'Society', 'World', 2, '2026-08-17T22:13:57.906969'::timestamptz, '2026-08-25T16:20:25'::timestamptz, '2026-08-25T16:20:25'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15390', 'Focus on Donald Trump''s Aide Natalie Harp Amidst Media Scrutiny', 'डोनाल्ड ट्रंप की सहयोगी नताली हार्प मीडिया की जांच के दायरे में', 'Politics', 'World', 2, '2026-08-18T06:18:22.772675'::timestamptz, '2026-08-23T08:21:50.010326'::timestamptz, '2026-08-23T08:21:50.010326'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15365', 'Economists Warn of Stock Market Correction', 'अर्थशास्त्रियों ने शेयर बाजार में सुधार की चेतावनी दी', 'Economy', 'World', 2, '2026-08-18T05:22:29.472840'::timestamptz, '2026-08-23T08:20:10.967009'::timestamptz, '2026-08-23T08:20:10.967009'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-8956', 'Palestinian-American returns to West Bank home under settler siege', 'फिलिस्तीनी-अमेरिकी इजरायली बसने वालों की घेराबंदी के तहत वेस्ट बैंक स्थित अपने घर लौटे', 'Crime & Law', 'World', 11, '2026-07-26T02:07:39.802242'::timestamptz, '2026-08-23T08:19:33.458295'::timestamptz, '2026-08-23T08:19:33.458295'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13425', 'Chinese Robot Maker Unitree Launches IPO in Shanghai', 'चीनी रोबोट निर्माता यूनिट्री शंघाई में आईपीओ लॉन्च कर रही है', 'Economy', 'World', 3, '2026-08-13T05:00:12.845574'::timestamptz, '2026-08-23T08:19:07.419231'::timestamptz, '2026-08-23T08:19:07.419231'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15359', 'Iran Bars French Embassy Staff, Detains Artists', 'ईरान ने फ्रांसीसी दूतावास के कर्मचारियों को रोका, कलाकारों को हिरासत में लिया', 'Politics', 'World', 2, '2026-08-17T22:13:57.555231'::timestamptz, '2026-08-23T08:18:51.501152'::timestamptz, '2026-08-23T08:18:51.501152'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11470', 'Australia and Bangladesh Cricket Teams Prepare for Second Test', 'ऑस्ट्रेलिया और बांग्लादेश क्रिकेट टीमों के बीच दूसरे टेस्ट की तैयारी', 'Sports', 'World', 7, '2026-08-07T06:43:28.782206'::timestamptz, '2026-08-23T08:18:30.477203'::timestamptz, '2026-08-23T08:18:30.477203'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11528', 'Emraan Hashmi Film ''Awarapan 2'' Crosses ₹170 Crore Worldwide', 'इमरान हाशमी की फिल्म ''अवारापन 2'' ने दुनिया भर में कमाए ₹170 करोड़', 'Entertainment', 'World', 5, '2026-08-06T13:59:17.479675'::timestamptz, '2026-08-23T00:00:00'::timestamptz, '2026-08-23T00:00:00'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11850', 'Bangladesh Considers Joining Saudi-Pakistan-Turkey Defense Pact', 'बांग्लादेश सऊदी-पाकिस्तान-तुर्की रक्षा संधि में शामिल होने पर विचार कर रहा है', 'Politics', 'World', 8, '2026-08-08T06:10:49.699133'::timestamptz, '2026-08-22T16:27:09'::timestamptz, '2026-08-22T16:27:09'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14828', 'Australia''s Capital Joins Gun Buyback After Bondi Attack', 'बॉन्डी हमले के बाद ऑस्ट्रेलिया की राजधानी गन बायबैक में शामिल', 'Crime & Law', 'World', 2, '2026-08-17T06:16:43.661751'::timestamptz, '2026-08-22T10:09:08'::timestamptz, '2026-08-22T10:09:08'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15527', 'Penn State Fraternity Members Charged in Alleged Cocaine Ring', 'पेन स्टेट फ्रेटरनिटी सदस्यों पर कथित कोकीन रैकेट में आरोप', 'Crime & Law', 'World', 2, '2026-08-18T05:22:29.533713'::timestamptz, '2026-08-22T05:35:26.383779'::timestamptz, '2026-08-22T05:35:26.383779'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13470', 'Iran Signals Readiness for Wider Conflict Amid Shifting Ceasefire Dynamics', 'ईरान ने बदलती युद्धविराम गतिशीलता के बीच व्यापक संघर्ष की तैयारी का संकेत दिया', 'International', 'World', 3, '2026-08-12T07:23:10.046742'::timestamptz, '2026-08-22T05:28:14.498530'::timestamptz, '2026-08-22T05:28:14.498530'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11875', 'Two students dead in Philippines school shooting', 'फिलीपींस में स्कूल गोलीबारी में दो छात्रों की मौत', 'Crime & Law', 'World', 4, '2026-08-08T06:10:52.010665'::timestamptz, '2026-08-22T05:25:28.460325'::timestamptz, '2026-08-22T05:25:28.460325'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14568', 'RBI Closes Dollar Swap Window, Impacting Rupee and Bond Yields', 'RBI ने डॉलर स्वैप विंडो बंद की, रुपये और बॉन्ड यील्ड पर असर', 'Economy', 'India', 2, '2026-08-17T22:13:07.431154'::timestamptz, '2026-08-22T05:25:04.807792'::timestamptz, '2026-08-22T05:25:04.807792'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14461', 'India Loses to England in Hockey World Cup Match', 'हॉकी विश्व कप मैच में भारत इंग्लैंड से हारा', 'Sports', 'India', 2, '2026-08-16T23:57:10.702067'::timestamptz, '2026-08-22T05:25:04.269810'::timestamptz, '2026-08-22T05:25:04.269810'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14415', 'Afghan women face repression and limited legal recourse under Taliban rule', 'तालिबान शासन में अफगान महिलाओं को दमन और सीमित कानूनी राहत का सामना', 'Society', 'World', 2, '2026-08-16T00:35:13.420373'::timestamptz, '2026-08-21T17:31:11'::timestamptz, '2026-08-21T17:31:11'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14379', 'Chamoli Tunnel Accident: Search Continues for Two Missing Workers', 'चमोली सुरंग दुर्घटना: दो लापता श्रमिकों की तलाश जारी', 'Crime & Law', 'India', 2, '2026-08-14T17:48:11.114781'::timestamptz, '2026-08-20T00:56:33.973557'::timestamptz, '2026-08-20T00:56:33.973557'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11952', 'Two More Air India Pilots Fail Preliminary Drug Tests', 'दो और एयर इंडिया पायलट प्रारंभिक दवा परीक्षण में विफल', 'Crime & Law', 'India', 8, '2026-08-09T11:01:46.386112'::timestamptz, '2026-08-20T00:56:33.768900'::timestamptz, '2026-08-20T00:56:33.768900'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14915', 'Man Charged with Manslaughter in Dog Bite Fatality', 'कुत्ते के काटने से हुई मौत के मामले में व्यक्ति पर गैर इरादतन हत्या का आरोप', 'Crime & Law', 'World', 2, '2026-08-18T03:37:38.940112'::timestamptz, '2026-08-20T00:56:33.569756'::timestamptz, '2026-08-20T00:56:33.569756'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13681', 'China Holds Funeral for Former Premier Zhu Rongji Amid Tight Security', 'पूर्व चीनी प्रीमियर झू रोंगजी का अंतिम संस्कार, कड़ी सुरक्षा के बीच संपन्न', 'Politics', 'World', 3, '2026-08-13T23:17:35.261469'::timestamptz, '2026-08-20T00:56:33.515846'::timestamptz, '2026-08-20T00:56:33.515846'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14675', 'Belgian Workers Find $10 Million in Gold Coins and Bars', 'बेल्जियम में मजदूरों को मिले 10 मिलियन डॉलर के सोने के सिक्के और बार', 'Crime & Law', 'World', 2, '2026-08-16T23:57:12.920431'::timestamptz, '2026-08-20T00:56:32.413275'::timestamptz, '2026-08-20T00:56:32.413275'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12573', 'Luigi Mangione State Murder Trial Postponed', 'लुइगी मैंगियोन पर हत्या का राज्य मुकदमा स्थगित', 'Crime & Law', 'World', 3, '2026-08-08T21:36:15.020191'::timestamptz, '2026-08-20T00:56:31.718494'::timestamptz, '2026-08-20T00:56:31.718494'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15191', 'Actress Hayden Panettiere Dies at 36; Career and Personal Life Recalled', 'अभिनेत्री हेडेन पनेटीयर का 36 की उम्र में निधन; करियर और निजी जीवन को याद किया गया', 'Society', 'World', 3, '2026-08-17T22:13:05.854202'::timestamptz, '2026-08-20T00:56:31.447677'::timestamptz, '2026-08-20T00:56:31.447677'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14733', 'NTA Overhaul Ordered After UGC-NET Exam Errors, Staff Sacked', 'यूजीसी-नेट परीक्षा में गड़बड़ी के बाद एनटीए का कायापलट, कर्मचारियों की छंटनी', 'Crime & Law', 'India', 2, '2026-08-17T05:08:06.032470'::timestamptz, '2026-08-20T00:56:30.951690'::timestamptz, '2026-08-20T00:56:30.951690'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-9679', 'FIFA COO Kevin Lamour Departs Amid Criticism of President Infantino', 'फीफा सीओओ केविन लामौर का राष्ट्रपति इंफेंटिनो की आलोचना के बीच पद छोड़ना', 'Politics', 'World', 14, '2026-07-29T01:03:58.242262'::timestamptz, '2026-08-20T00:56:29.325083'::timestamptz, '2026-08-20T00:56:29.325083'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13987', 'US Border Wall Construction Halted Amidst Public Opposition', 'जनता के विरोध के बीच अमेरिकी सीमा दीवार का निर्माण रोका गया', 'Crime & Law', 'World', 5, '2026-08-13T04:08:31.873758'::timestamptz, '2026-08-19T16:38:34'::timestamptz, '2026-08-19T16:38:34'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15452', 'Footballer Jamal Musiala collapses on pitch, reveals neurological dysfunction', 'फुटबॉलर जमाल मुसियाला पिच पर गिर पड़े, ''न्यूरोलॉजिकल डिसफंक्शन'' का खुलासा', 'Sports', 'World', 2, '2026-08-17T23:06:13.237938'::timestamptz, '2026-08-19T15:08:08'::timestamptz, '2026-08-19T15:08:08'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14814', 'UAE Air Defenses Detect Missile, Iran Denies Attack; Qatar Returns Pilot Remains', 'यूएई की वायु रक्षा प्रणाली ने मिसाइल का पता लगाया, ईरान ने हमले से इनकार किया; कतर ने पायलट के अवशेष लौटाए', 'Crime & Law', 'World', 2, '2026-08-17T01:00:20.774166'::timestamptz, '2026-08-19T04:26:31'::timestamptz, '2026-08-19T04:26:31'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15447', 'Trial begins for ex-wife and new husband in Microsoft executive murder case', 'माइक्रोसॉफ्ट कार्यकारी हत्या मामले में पूर्व पत्नी और नए पति पर मुकदमा शुरू', 'Crime & Law', 'World', 2, '2026-08-18T03:37:39.250052'::timestamptz, '2026-08-18T23:11:00'::timestamptz, '2026-08-18T23:11:00'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14913', 'FDA Notices Issued Over Vimal Elaichi Advertisement', 'विमल इलायची विज्ञापन पर FDA ने जारी किए नोटिस', 'Crime & Law', 'India', 3, '2026-08-18T03:37:40.284397'::timestamptz, '2026-08-18T10:30:17.802783'::timestamptz, '2026-08-18T10:30:17.802783'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15341', 'CBI files chargesheet in Twisha Sharma death case', 'ट्विशा शर्मा मौत मामले में सीबीआई ने दायर की चार्जशीट', 'Crime & Law', 'India', 3, '2026-08-18T09:43:26.179464'::timestamptz, '2026-08-18T10:30:17.566413'::timestamptz, '2026-08-18T10:30:17.566413'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13098', 'Indonesia Earthquake: Thousands Displaced, Aid Efforts Underway', 'इंडोनेशिया भूकंप: हजारों विस्थापित, सहायता प्रयास जारी', 'Environment', 'World', 7, '2026-08-12T00:28:51.390465'::timestamptz, '2026-08-18T10:29:52.108895'::timestamptz, '2026-08-18T10:29:52.108895'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15266', 'Manipur Protests Demand NRC Before Census, CM Briefs Home Minister', 'मणिपुर में जनगणना से पहले एनआरसी की मांग को लेकर विरोध प्रदर्शन, सीएम ने गृह मंत्री को दी जानकारी', 'Society', 'India', 2, '2026-08-17T22:13:10.266931'::timestamptz, '2026-08-18T10:29:51.846033'::timestamptz, '2026-08-18T10:29:51.846033'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13133', 'Tata Sons AGM Adjourned Amidst Board Division Over Chairman''s Future', 'टाटा संस एजीएम स्थगित, चेयरमैन के भविष्य पर बोर्ड में मतभेद', 'Politics', 'India', 10, '2026-08-12T07:23:07.128812'::timestamptz, '2026-08-18T10:29:50.952060'::timestamptz, '2026-08-18T10:29:50.952060'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-9213', 'Tamil Nadu Government''s First 100 Days Reviewed by BJP Leaders', 'भाजपा नेताओं ने तमिलनाडु सरकार के पहले 100 दिनों की समीक्षा की', 'Politics', 'India', 9, '2026-07-29T00:31:15.708331'::timestamptz, '2026-08-18T10:29:50.233629'::timestamptz, '2026-08-18T10:29:50.233629'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15161', 'Trump Praises Indian Election System, Cites Voter ID; India Responds', 'ट्रंप ने भारतीय चुनाव प्रणाली की प्रशंसा की, वोटर आईडी का उल्लेख किया; भारत ने जवाब दिया', 'Politics', 'India', 3, '2026-08-18T03:37:37.335617'::timestamptz, '2026-08-18T10:29:48.814432'::timestamptz, '2026-08-18T10:29:48.814432'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15074', 'Trump Scales Back US-South Korea Military Drills, Allies Express Concern', 'ट्रंप ने अमेरिका-दक्षिण कोरिया सैन्य अभ्यास कम किए, सहयोगियों ने चिंता जताई', 'Politics', 'World', 4, '2026-08-17T03:04:20.216326'::timestamptz, '2026-08-18T10:29:48.521701'::timestamptz, '2026-08-18T10:29:48.521701'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11518', 'Kushner Discusses Hamas Disarmament and Gaza Reconstruction with Netanyahu', 'कुशनर ने नेतन्याहू के साथ हमास निरस्त्रीकरण और गाजा पुनर्निर्माण पर चर्चा की', 'Politics', 'World', 6, '2026-08-07T08:01:51.644375'::timestamptz, '2026-08-18T10:29:47.912755'::timestamptz, '2026-08-18T10:29:47.912755'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13949', 'Meta faces major US trial over child safety and platform addiction', 'मेटा बाल सुरक्षा और प्लेटफॉर्म की लत को लेकर बड़े अमेरिकी मुकदमे का सामना कर रहा है', 'Crime & Law', 'World', 3, '2026-08-13T05:52:51.126723'::timestamptz, '2026-08-18T10:29:47.731134'::timestamptz, '2026-08-18T10:29:47.731134'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15551', 'Eight Labourers Dead, Dozens Injured in Madhya Pradesh Road Accident', 'मध्य प्रदेश सड़क दुर्घटना में आठ मजदूरों की मौत, दर्जनों घायल', 'Crime & Law', 'India', 2, '2026-08-18T07:05:20.344621'::timestamptz, '2026-08-18T09:43:29.653911'::timestamptz, '2026-08-18T09:43:29.653911'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-9690', 'Spider-Man Film Sets New Box Office Record in India', 'स्पाइडर-मैन फिल्म ने भारत में बॉक्स ऑफिस रिकॉर्ड बनाया', 'Entertainment', 'India', 10, '2026-07-31T03:49:34.699927'::timestamptz, '2026-08-18T09:43:28.598819'::timestamptz, '2026-08-18T09:43:28.598819'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14590', 'Cristiano Ronaldo Suggests Retirement After 2026-27 Season', 'क्रिस्टियानो रोनाल्डो ने 2026-27 सीज़न के बाद संन्यास का संकेत दिया', 'Sports', 'World', 2, '2026-08-18T03:37:37.699698'::timestamptz, '2026-08-18T09:43:28.337266'::timestamptz, '2026-08-18T09:43:28.337266'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-7967', 'Trump Approval Rating Dips in New Poll', 'ट्रम्प की अनुमोदन रेटिंग नए सर्वेक्षण में गिरी', 'Politics', 'World', 22, '2026-07-18T16:44:40.374265'::timestamptz, '2026-08-18T09:43:27.451820'::timestamptz, '2026-08-18T09:43:27.451820'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11271', 'Badminton World Championships begin in India with focus on Indian players', 'भारतीय खिलाड़ियों पर ध्यान केंद्रित करते हुए भारत में बैडमिंटन विश्व चैंपियनशिप शुरू', 'Sports', 'India', 2, '2026-08-06T05:04:40.784076'::timestamptz, '2026-08-18T08:51:41.584449'::timestamptz, '2026-08-18T08:51:41.584449'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12456', 'Andhra Pradesh: Eight Fishermen Missing at Sea, Search Underway', 'आंध्र प्रदेश: आठ मछुआरे समुद्र में लापता, तलाशी अभियान जारी', 'Crime & Law', 'India', 2, '2026-08-09T12:12:42.675711'::timestamptz, '2026-08-18T08:51:40.687479'::timestamptz, '2026-08-18T08:51:40.687479'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15612', 'Five CRPF Personnel Injured in Jammu-Srinagar Highway Accident', 'जम्मू-श्रीनगर हाईवे पर दुर्घटना में पांच सीआरपीएफ कर्मी घायल', 'Crime & Law', 'India', 2, '2026-08-18T05:22:51.854351'::timestamptz, '2026-08-18T07:56:46.461050'::timestamptz, '2026-08-18T07:56:46.461050'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11410', 'Bangladesh Links PM Rahman''s India Visit to Hasina Extradition', 'बांग्लादेश ने पीएम रहमान की भारत यात्रा को हसीना के प्रत्यर्पण से जोड़ा', 'Politics', 'India', 4, '2026-08-06T05:04:33.011804'::timestamptz, '2026-08-18T07:56:45.068790'::timestamptz, '2026-08-18T07:56:45.068790'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11960', 'Voter List Updates Face Delays and Objections Across India', 'भारत भर में मतदाता सूची अद्यतन में देरी और आपत्तियां', 'Crime & Law', 'India', 3, '2026-08-08T15:38:40.490222'::timestamptz, '2026-08-18T07:05:22.719522'::timestamptz, '2026-08-18T07:05:22.719522'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14901', 'Former TMC MLA Asish Banerjee Found Dead; Suicide Note Mentions Political Pressure', 'पूर्व टीएमसी विधायक आशीष बनर्जी का शव मिला; सुसाइड नोट में राजनीतिक दबाव का जिक्र', 'Crime & Law', 'India', 2, '2026-08-16T22:50:14.549645'::timestamptz, '2026-08-18T07:05:22.195639'::timestamptz, '2026-08-18T07:05:22.195639'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15189', 'Nine Dead in Tarapith Hotel Fire; Safety Allegations Surface', 'তারাপিঠ হোটেল অগ্নিকাণ্ডে ৯ জনের মৃত্যু; নিরাপত্তা ব্যবস্থার অভিযোগ', 'Crime & Law', 'India', 2, '2026-08-17T23:05:33.899418'::timestamptz, '2026-08-18T06:18:23.119314'::timestamptz, '2026-08-18T06:18:23.119314'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13503', 'Food Safety Crackdowns and New Regulations Across India', 'भारत भर में खाद्य सुरक्षा कार्रवाई और नए नियम', 'Crime & Law', 'India', 2, '2026-08-14T17:48:06.962130'::timestamptz, '2026-08-18T06:18:21.026077'::timestamptz, '2026-08-18T06:18:21.026077'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-15435', 'Russian opposition leader jailed 11 years for anti-war remarks', 'रूसी विपक्षी नेता को युद्ध-विरोधी बयानों पर 11 साल की जेल', 'Crime & Law', 'World', 2, '2026-08-17T23:06:13.283560'::timestamptz, '2026-08-18T05:22:30.564422'::timestamptz, '2026-08-18T05:22:30.564422'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14298', 'Islam Makhachev defeats Ian Machado Garry in UFC title fight', 'इस्लाम मखाचेव ने यूएफसी खिताब लड़ाई में इयान मचाडो गैरी को हराया', 'Sports', 'World', 2, '2026-08-14T16:09:28.742673'::timestamptz, '2026-08-18T04:28:19.634118'::timestamptz, '2026-08-18T04:28:19.634118'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12238', 'Lake Powell Hits Record Low Amid Colorado River Water Crisis', 'कोलोराडो नदी संकट के बीच पावेल झील रिकॉर्ड निचले स्तर पर', 'Environment', 'World', 2, '2026-08-11T18:39:29.180951'::timestamptz, '2026-08-18T04:28:19.136426'::timestamptz, '2026-08-18T04:28:19.136426'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12974', 'Tupac Shakur murder trial begins in Las Vegas', 'टुपाक शकूर हत्या मामले में लास वेगास में सुनवाई शुरू', 'Crime & Law', 'World', 2, '2026-08-12T23:24:40.750035'::timestamptz, '2026-08-18T04:28:17.189230'::timestamptz, '2026-08-18T04:28:17.189230'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14612', 'Tropical Storm Lala damages Hawaii, causes widespread power outages', 'उष्णकटिबंधीय तूफान लाला ने हवाई को क्षतिग्रस्त किया, व्यापक बिजली कटौती हुई', 'Environment', 'World', 2, '2026-08-17T03:04:20.527785'::timestamptz, '2026-08-18T04:28:16.569321'::timestamptz, '2026-08-18T04:28:16.569321'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13040', 'Europe Faces Severe Drought Impacting Rivers and Economy', 'यूरोप गंभीर सूखे का सामना कर रहा है, नदियाँ और अर्थव्यवस्था प्रभावित', 'Environment', 'World', 3, '2026-08-12T23:24:39.451342'::timestamptz, '2026-08-18T03:38:24.330655'::timestamptz, '2026-08-18T03:38:24.330655'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14334', 'PM Modi Addresses Nation on 80th Independence Day, Focuses on Youth and Self-Reliance', 'प्रधानमंत्री मोदी ने 80वें स्वतंत्रता दिवस पर राष्ट्र को संबोधित किया, युवाओं और आत्मनिर्भरता पर ध्यान केंद्रित किया', 'Politics', 'India', 3, '2026-08-14T17:48:07.403471'::timestamptz, '2026-08-18T03:37:40.312968'::timestamptz, '2026-08-18T03:37:40.312968'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12158', 'Maharashtra Food Delivery Warehouses Face Action Over Hygiene Violations', 'महाराष्ट्र में खाद्य वितरण गोदामों पर स्वच्छता उल्लंघन के मामले में कार्रवाई', 'Crime & Law', 'India', 3, '2026-08-11T19:55:19.338433'::timestamptz, '2026-08-18T03:37:39.929241'::timestamptz, '2026-08-18T03:37:39.929241'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11939', 'Houthis Claim Missile Attack on Saudi Vessels in Red Sea', 'हूती विद्रोहियों ने लाल सागर में सऊदी जहाजों पर मिसाइल हमले का दावा किया', 'Crime & Law', 'World', 3, '2026-08-08T10:48:15.889168'::timestamptz, '2026-08-18T03:37:39.901481'::timestamptz, '2026-08-18T03:37:39.901481'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-8045', 'DR Congo Ebola Outbreak Becomes Deadliest, Spreading Rapidly', 'डीआर कांगो में इबोला का प्रकोप सबसे घातक, तेजी से फैल रहा है', 'Health', 'World', 7, '2026-07-29T00:31:12.870505'::timestamptz, '2026-08-18T03:37:39.752917'::timestamptz, '2026-08-18T03:37:39.752917'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12143', 'Lindsay Clancy Murder Trial: Mother Testifies Amidst Defense and Fundraising', 'लिंडसे क्लैंसी हत्या का मुकदमा: मां की गवाही, बचाव और धन उगाहने के बीच', 'Crime & Law', 'World', 3, '2026-08-08T17:53:43.734782'::timestamptz, '2026-08-18T03:37:36.195882'::timestamptz, '2026-08-18T03:37:36.195882'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13229', 'Cristiano Ronaldo and Georgina Rodriguez hold private living room wedding', 'क्रिस्टियानो रोनाल्डो और जॉर्जियाना रोड्रिगेज ने लिविंग रूम में की निजी शादी', 'Society', 'World', 3, '2026-08-12T06:40:50.607512'::timestamptz, '2026-08-17T23:05:36.298356'::timestamptz, '2026-08-17T23:05:36.298356'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14898', 'Actress Ananya Raj Dies at 27 After Health Battle', 'अभिनेत्री अनन्या राज का 27 साल की उम्र में निधन, स्वास्थ्य संबंधी समस्याओं से जूझ रही थीं', 'Society', 'India', 2, '2026-08-16T22:50:15.761409'::timestamptz, '2026-08-17T23:05:36.207980'::timestamptz, '2026-08-17T23:05:36.207980'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14478', 'US Accuses India and 40+ Nations of Aiding China''s Tariff Evasion', 'अमेरिका का भारत और 40+ देशों पर चीन की टैरिफ चोरी में मदद करने का आरोप', 'Economy', 'India', 2, '2026-08-14T18:48:29.685400'::timestamptz, '2026-08-17T22:13:10.106459'::timestamptz, '2026-08-17T22:13:10.106459'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14548', 'BBC Seeks US Court Help for Testimony in Trump Family Defamation Case', 'बीबीसी ने ट्रम्प परिवार के मानहानि मामले में गवाही के लिए अमेरिकी अदालत से मदद मांगी', 'Crime & Law', 'World', 2, '2026-08-16T22:49:13.239480'::timestamptz, '2026-08-17T22:13:07.710792'::timestamptz, '2026-08-17T22:13:07.710792'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13753', 'Cambridge Professor Jason Arday Found Dead Amid Plagiarism Scrutiny', 'कैम्ब्रिज के प्रोफेसर जेसन अर्डे साहित्यिक चोरी की जांच के बीच मृत पाए गए', 'Crime & Law', 'World', 2, '2026-08-13T00:33:17.679749'::timestamptz, '2026-08-17T22:13:06.646442'::timestamptz, '2026-08-17T22:13:06.646442'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-7968', 'India''s Parliament Monsoon Session Concludes Amid Disruptions and Protests', 'भारत के संसद का मानसून सत्र हंगामे और विरोध के बीच संपन्न', 'Politics', 'India', 20, '2026-07-19T12:23:35.516299'::timestamptz, '2026-08-17T04:05:56.100777'::timestamptz, '2026-08-17T04:05:56.100777'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12820', 'Delhi High Court to hear CBI plea on liquor policy case discharge', 'दिल्ली हाई कोर्ट शराब नीति मामले में डिस्चार्ज पर सीबीआई की याचिका पर सुनवाई करेगा', 'Crime & Law', 'India', 2, '2026-08-09T12:13:28.642032'::timestamptz, '2026-08-17T04:05:53.187661'::timestamptz, '2026-08-17T04:05:53.187661'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13691', 'New Dinosaur Thriller ''The End of Oak Street'' Receives Mixed Reviews', 'नई डायनासोर थ्रिलर ''द एंड ऑफ ओक स्ट्रीट'' को मिली-जुली समीक्षाएं', 'Entertainment', 'World', 3, '2026-08-12T23:25:27.141000'::timestamptz, '2026-08-17T02:02:53.066920'::timestamptz, '2026-08-17T02:02:53.066920'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12117', 'Trump Appeals to Supreme Court Over White House Ballroom Construction', 'ट्रम्प ने व्हाइट हाउस बैरकूम निर्माण पर सुप्रीम कोर्ट से अपील की', 'Crime & Law', 'World', 2, '2026-08-10T00:32:32.955671'::timestamptz, '2026-08-17T00:35:30.004234'::timestamptz, '2026-08-17T00:35:30.004234'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14250', 'Luigi Mangione Pleads Guilty to Federal Charges in CEO''s Killing', 'लुइगी मैंगियोन ने सीईओ की हत्या के संघीय आरोपों में दोषी ठहराया', 'Crime & Law', 'World', 3, '2026-08-14T00:27:13.758764'::timestamptz, '2026-08-16T23:57:13.886896'::timestamptz, '2026-08-16T23:57:13.886896'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13680', 'White House Press Secretary Karoline Leavitt''s Tenure Discussed', 'व्हाइट हाउस प्रेस सेक्रेटरी कैरोलिन लीविट के कार्यकाल पर चर्चा', 'Politics', 'World', 4, '2026-08-13T00:58:20.333822'::timestamptz, '2026-08-16T23:57:13.102475'::timestamptz, '2026-08-16T23:57:13.102475'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13159', 'Kerala Forms SIT to Probe GST Evasion Claim Over Messi Visit', 'मेसी की यात्रा पर जीएसटी चोरी के आरोपों की जांच के लिए केरल ने एसआईटी का गठन किया', 'Crime & Law', 'India', 3, '2026-08-12T08:03:33.790235'::timestamptz, '2026-08-16T22:50:18.215604'::timestamptz, '2026-08-16T22:50:18.215604'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-9917', 'Migrants Protest in Spain''s Ceuta, Demand Asylum', 'स्पेन के सेउटा में प्रवासियों का विरोध, शरण की मांग', 'Crime & Law', 'World', 10, '2026-07-31T20:29:58.474229'::timestamptz, '2026-08-16T22:49:22.494478'::timestamptz, '2026-08-16T22:49:22.494478'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-10483', 'Romania Shuts Nuclear Plant Due to Record-Low Danube Water Levels', 'रोमानिया ने डेन्यूब नदी के रिकॉर्ड-निम्न जल स्तर के कारण परमाणु संयंत्र बंद किया', 'Environment', 'World', 3, '2026-08-04T05:32:47.724941'::timestamptz, '2026-08-16T22:49:18.034317'::timestamptz, '2026-08-16T22:49:18.034317'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12982', 'Wisconsin Democratic Primary Sees Moderate David Crowley Defeat Progressive Francesca Hong', 'डेमोक्रेटिक प्राइमरी में डेविड क्रॉली ने प्रोग्रेसिव फ्रांसेस्का होंग को हराया', 'Politics', 'World', 2, '2026-08-12T07:23:07.308708'::timestamptz, '2026-08-16T22:49:17.312923'::timestamptz, '2026-08-16T22:49:17.312923'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13284', 'Trump''s Secret Departure from Plane Noted by Onboard Individuals', 'ट्रम्प का विमान से गुप्त प्रस्थान, विमान में सवार लोगों ने की पुष्टि', 'Politics', 'World', 5, '2026-08-12T01:47:38.030400'::timestamptz, '2026-08-16T00:37:46.361710'::timestamptz, '2026-08-16T00:37:46.361710'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-14065', 'UNSC report attributes Red Fort blast to Al-Qaeda offshoot', 'संयुक्त राष्ट्र सुरक्षा परिषद की रिपोर्ट में लाल किला विस्फोट के लिए अल-कायदा के सहयोगी को जिम्मेदार ठहराया गया', 'Crime & Law', 'India', 2, '2026-08-13T07:42:57.648218'::timestamptz, '2026-08-16T00:35:23.462291'::timestamptz, '2026-08-16T00:35:23.462291'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13444', 'Total Solar Eclipse Visible Across Spain, Drawing Large Crowds', 'स्पेन में दिखा दुर्लभ पूर्ण सूर्य ग्रहण, लाखों लोग हुए साक्षी', 'Society', 'World', 3, '2026-08-12T06:40:50.260922'::timestamptz, '2026-08-16T00:35:21.373939'::timestamptz, '2026-08-16T00:35:21.373939'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12762', 'India Prepares for 80th Independence Day with Enhanced Security Measures', 'भारत 80वें स्वतंत्रता दिवस के लिए बढ़ी हुई सुरक्षा व्यवस्था के साथ तैयार', 'Crime & Law', 'India', 3, '2026-08-12T23:24:42.413227'::timestamptz, '2026-08-16T00:35:18.985259'::timestamptz, '2026-08-16T00:35:18.985259'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13443', 'US agency plans $20M purchase of electric shock gloves for officers', 'अमेरिकी एजेंसी अधिकारियों के लिए इलेक्ट्रिक शॉक दस्तानों की $20 मिलियन की खरीद की योजना बना रही है', 'Crime & Law', 'India', 2, '2026-08-13T07:42:57.831777'::timestamptz, '2026-08-16T00:35:17.319874'::timestamptz, '2026-08-16T00:35:17.319874'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13700', 'Two US Army Soldiers Die in Texas Helicopter Crash', 'टेक्सास में हेलीकॉप्टर दुर्घटना में दो अमेरिकी सैनिकों की मौत', 'Crime & Law', 'World', 2, '2026-08-14T00:08:36.521481'::timestamptz, '2026-08-16T00:35:16.353127'::timestamptz, '2026-08-16T00:35:16.353127'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-8540', 'India, Pakistan Trade Barbs Over Indus Waters Treaty Amid Terror Claims', 'आतंकवाद के आरोपों के बीच सिंधु जल संधि पर भारत-पाकिस्तान में जुबानी जंग', 'Politics', 'India', 3, '2026-07-23T11:19:46.056781'::timestamptz, '2026-08-15T00:22:56.448628'::timestamptz, '2026-08-15T00:22:56.448628'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-8807', 'Rahul Gandhi Criticizes PM Modi''s Foreign Policy, BJP Responds', 'राहुल गांधी ने पीएम मोदी की विदेश नीति की आलोचना की, भाजपा ने जवाब दिया', 'Politics', 'India', 18, '2026-07-25T22:35:33.492341'::timestamptz, '2026-08-14T17:48:08.026884'::timestamptz, '2026-08-14T17:48:08.026884'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11746', 'Parliamentary Committee Reviews FCRA Bill Amid Multiple Issues', 'संसदीय समिति विभिन्न मुद्दों के बीच एफसीआरए विधेयक की समीक्षा करेगी', 'Crime & Law', 'India', 3, '2026-08-08T21:35:43.808722'::timestamptz, '2026-08-14T00:27:14.266323'::timestamptz, '2026-08-14T00:27:14.266323'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13018', 'Trump switched planes in Turkey due to Iran missile threat, reports say', 'ईरान के मिसाइल खतरे के कारण तुर्की में ट्रंप ने बदला था विमान, रिपोर्टों में खुलासा', 'Crime & Law', 'World', 3, '2026-08-11T21:02:00.090328'::timestamptz, '2026-08-14T00:27:12.135396'::timestamptz, '2026-08-14T00:27:12.135396'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12978', 'Russia Frees Former US Marine Robert Gilman After Over Four Years', 'रूस ने चार साल से अधिक समय बाद पूर्व अमेरिकी मरीन रॉबर्ट गिलमैन को रिहा किया', 'Crime & Law', 'World', 2, '2026-08-12T23:24:37.134553'::timestamptz, '2026-08-14T00:08:38.297911'::timestamptz, '2026-08-14T00:08:38.297911'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-9500', 'Multiple Entrance Exam Seat Allotment Results Released', 'विभिन्न प्रवेश परीक्षाओं के सीट आवंटन परिणाम जारी', 'Society', 'India', 5, '2026-08-01T08:00:37.616411'::timestamptz, '2026-08-13T23:17:40.317258'::timestamptz, '2026-08-13T23:17:40.317258'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-11546', 'Total Solar Eclipse Visible Across Europe, NASA Images Shared', 'यूरोप में दिखा पूर्ण सूर्य ग्रहण, नासा ने साझा की तस्वीरें', 'Science & Tech', 'World', 6, '2026-08-09T02:03:13.793015'::timestamptz, '2026-08-13T23:17:36.246188'::timestamptz, '2026-08-13T23:17:36.246188'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-13701', 'Kangana Ranaut Defends Remarks on Naseeruddin Shah and Bollywood', 'कंगना रनौत ने नसीरुद्दीन शाह और बॉलीवुड पर की गई टिप्पणियों का बचाव किया', 'Politics', 'India', 2, '2026-08-12T23:25:27.395537'::timestamptz, '2026-08-13T23:17:36.164223'::timestamptz, '2026-08-13T23:17:36.164223'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-12637', 'Australia Reports First H5N1 Bird Flu Case in Tasmania', 'तस्मानिया में बर्ड फ्लू का पहला H5N1 मामला दर्ज', 'Health', 'World', 2, '2026-08-09T11:02:07.393733'::timestamptz, '2026-08-13T23:17:35.811686'::timestamptz, '2026-08-13T23:17:35.811686'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;

INSERT INTO public.storylines (id, title, title_hi, topic, region, n_events, starts_at, ends_at, updated_at) VALUES ('sl-10132', 'Pakistani National Arrested in West Bengal with Suspected Spy Materials', 'पश्चिम बंगाल में संदिग्ध जासूसी सामग्री के साथ पाकिस्तानी नागरिक गिरफ्तार', 'Crime & Law', 'India', 3, '2026-08-01T17:38:50.473622'::timestamptz, '2026-08-13T08:57:39.855354'::timestamptz, '2026-08-13T08:57:39.855354'::timestamptz) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_hi = EXCLUDED.title_hi, topic = EXCLUDED.topic, region = EXCLUDED.region, n_events = EXCLUDED.n_events, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at, updated_at = EXCLUDED.updated_at;
